name: cs_545_jahnu_best
description: "CS 545 Jahnu Best."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  permission_handler: ^11.0.0
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
